---
# tasks file for apache

- name: Ensure httpd packages are installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - php
    - git
    - php-mysqlnd
  tags: apache_installer

- name: Ensure SELinux allows httpd connections to a remote database
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true

- name: Ensure httpd service is started and enabled
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
