---
- name: Implementing Handlers
  hosts: web_servers

  pre_tasks:
    - name: Configuring Apache
      ansible.builtin.include_tasks: apache.yml

    - name: Setting web port and zone for firewall
      ansible.builtin.set_fact:
        web_port: 80/tcp
        web_zone: public
      changed_when: true
      notify: display variables

  roles:
    - role: firewall

  post_tasks:
  - name: Ensure the web content is copied
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/
    notify: verify connectivity

  handlers:
  - name: Showing the web port configured as pre_task
    ansible.builtin.debug:
      var: web_port
    listen: display variables

  - name: Showing the web zone configured as pre_task
    ansible.builtin.debug:
      var: web_zone
    listen: display variables

  - name: verify connectivity
    ansible.builtin.uri:
      url: http://{{ ansible_facts['fqdn'] }}
      status_code: 200
    become: false
