---
# tasks file for haproxy

- name: Ensure haproxy packages are present
  ansible.builtin.yum:
    name:
      - haproxy
      - socat
    state: present

- name: Ensure haproxy is started and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Ensure haproxy configuration is set
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: 
    - reload haproxy
    - haproxy filehandler
