---
# handlers file for haproxy

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: haproxy filehandler
  ansible.builtin.copy:
    content: "Reloaded\n"
    dest: /tmp/haproxy.status
