---
- name: Update Webservers
  hosts: localhost  # web_servers  # all, localhost

# When the number of failed hosts in a batch exceed this percentage,
#  Ansible halts playbook execution.
# To implement a "fail fast" strategy, set the max_fail_percentage to a value of zero.
  # max_fail_percentage: 30%

# page 201 no hosts chart
  serial: 2
#  serial: 25%
#  serial:
#    - 1
#    - 10%
#    - 25% # repeat until all hosts are processed
  tasks:
  - debug:
      msg: "Testing rolling update task 1"

  - debug:
      msg: "Testing rolling update task 2"
#    run_once: yes
#    delegate_to: localhost  # run once per batch







#  - debug:
#      msg: "{{ ansible_play_batch }}"
#      msg: "{{ ansible_play_hosts }}"

