---
# tasks file for webapp

- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ webapp_content_dir }}"
    state: directory

- name: Customize index.php
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ webapp_content_dir }}/index.html"
    owner: root
    group: root
    mode: '0644'
