---
- name: Setup web services
  hosts: localhost
  tags:
  - setup # Tag an entire play
  tasks:
  - name: Install http daemon
    yum:
      name: httpd
      state: present

  - block:
    - name: Ensure httpd packages are installed
      yum:
        name:
        - httpd
        - php
        - git
        - php-mysqlnd
        state: present

    - name: Ensure SELinux allows httpd connections to a remote database
      seboolean:
        name: httpd_can_network_connect_db
        state: true
        persistent: true

    - name: Ensure httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
    tags:  # Tag a block of tasks
    - webserver
