---
# special tags always, never
# Additional special tags tagged, untagged, all
# 21_tagging_resources.yml

- name: Install application
  hosts: localhost
  vars:
    packages:
      - postfix
      - mariadb-server

  tasks:
#  - name: Ensure that packages are installed
#    yum:
#      name: "{{ packages }}"
#      state: installed
#    tags:  # Tag each task
#    - install
#    check_mode: yes

  - name: print hello
    debug: 
      msg: "Hwello World!"
    tags:
     - db_servers

  - name: print hello 1
    debug: 
      msg: "Hwello World!"
    tags:
     - lb_servers

  - name: print hello 2
    debug: 
      msg: "Hwello World!"
    tags:
     - webapp
     - appserver
     - dbserver

#  - name: Include common web services tasks
#    include_tasks: common.yml
#    tags: # the included task file is tagged
#    - webproxy
#    - webserver

