---
# tasks file for firewall

- name: Ensure Firewall Port Configuration
  ansible.posix.firewalld:
    zone: "{{ item['zone'] | default(omit) }}"
    permanent: true
    state: "{{ item['state'] | default('enabled') }}"
    port: "{{ item['port'] }}"
    immediate: true
  loop: "{{ firewall_rules }}"
  notify: reload firewalld
  when: item['port'] is defined
  become: true
