download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/community/collections/artifacts/community-general-6.1.0.tar.gz
format_version: 1.0.0
name: general
namespace: community
server: https://hub.lab.example.com/api/galaxy/content/community/
signatures: []
version: 6.1.0
version_url: /api/galaxy/content/community/v3/plugin/ansible/content/community/collections/index/community/general/versions/6.1.0/
